name: riverpod_tamplates
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter 

  cupertino_icons:
  core_kit:
    path: C:/Users/KmMuzahid/Documents/others/core_kit

  flutter_riverpod:
  riverpod_annotation:
  auto_route:
  flutter_secure_storage: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint:
  core_kit_lints:
    path: C:/Users/KmMuzahid/Documents/others/core_kit/tools/custom_lint

  riverpod_generator:
  riverpod_lint:
  build_runner: 
  auto_route_generator: 
  flutter_gen_runner:
  flutter_lints: 
  flutter_launcher_icons: 
  change_app_package_name: ^1.5.0 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/nav/
